apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    app: app1
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool-http
      protocol: TCP
      port: 9002
      targetPort: 8080
