apiVersion: v1
kind: Service
metadata:
  name: svc-ex
spec:
  selector:
    app: app1
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30001
  type: NodePort
