apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
  labels:
    app: zd2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zd2
  template:
    metadata:
      labels:
        app: zd2
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
      initContainers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c", "nslookup svc2.default.svc.cluster.local"]
