apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    app: deployment
  ports:
    - name: svc-nginx
      port: 80
      targetPort: 80
    - name: svc-multitool
      port: 8080
      targetPort: 8080
